import { Category, Product, Review, Coupon, StoreSettings, User, Order } from '../src/types.js';

export const initialCategories: Category[] = [
  {
    id: "cat-3piece",
    name: "3 Piece",
    nameBn: "থ্রি-পিস",
    slug: "3-piece",
    description: "Exclusive lawn, cotton, georgette and silk embroidered 3-piece sets with matching dupattas and pants.",
    image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80",
    featured: true,
    displayOrder: 1,
  },
  {
    id: "cat-kameez",
    name: "Kameez",
    nameBn: "কামিজ",
    slug: "kameez",
    description: "Chic single-piece designer kameez tailored for effortless everyday and semi-formal elegance.",
    image: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80",
    featured: true,
    displayOrder: 2,
  },
  {
    id: "cat-saree",
    name: "Saree",
    nameBn: "শাড়ি",
    slug: "saree",
    description: "Handcrafted traditional Jamdani, Katan, Muslin, Pure Silk, and feather-light Georgette party sarees.",
    image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=800&q=80",
    featured: true,
    displayOrder: 3,
  },
  {
    id: "cat-hijab",
    name: "Hijab",
    nameBn: "হিজাব",
    slug: "hijab",
    description: "Premium breathable chiffon, modal cotton, luxury crinkle and silk hijabs with non-slip texture.",
    image: "https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?w=800&q=80",
    featured: true,
    displayOrder: 4,
  },
  {
    id: "cat-abaya",
    name: "Abaya",
    nameBn: "আবায়া",
    slug: "abaya",
    description: "Modern modest abayas, kimonos, and front-open borkas crafted in imported Dubai Nidha fabric.",
    image: "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=800&q=80",
    featured: true,
    displayOrder: 5,
  },
  {
    id: "cat-kurti",
    name: "Kurti",
    nameBn: "কুর্তি",
    slug: "kurti",
    description: "Comfortable, vibrant floral and embroidered tunics perfect for university, work and festive outings.",
    image: "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=800&q=80",
    featured: true,
    displayOrder: 6,
  },
  {
    id: "cat-salwar",
    name: "Salwar Kameez",
    nameBn: "সেলোয়ার কামিজ",
    slug: "salwar-kameez",
    description: "Regal silhouettes with heavy zori embroidery, scalloped borders and handcrafted motifs.",
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&q=80",
    featured: false,
    displayOrder: 7,
  },
  {
    id: "cat-bags",
    name: "Bags",
    nameBn: "ব্যাগ",
    slug: "bags",
    description: "Artisanal party potlis, clutches, structured handbags and spacious totes made for stylish women.",
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=80",
    featured: true,
    displayOrder: 8,
  },
  {
    id: "cat-jewellery",
    name: "Jewellery",
    nameBn: "গহনা",
    slug: "jewellery",
    description: "Handmade bridal and festive Kundan chokers, jhumkas, meenakari bangles, and pearl necklaces.",
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80",
    featured: true,
    displayOrder: 9,
  },
  {
    id: "cat-shoes",
    name: "Shoes",
    nameBn: "জুতা",
    slug: "shoes",
    description: "Hand-embroidered zardozi kolhapuris, pointed kitten heels and comfortable festive khussas.",
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80",
    featured: false,
    displayOrder: 10,
  },
  {
    id: "cat-accessories",
    name: "Accessories",
    nameBn: "এক্সেসরিজ",
    slug: "accessories",
    description: "Magnetic hijab pins, silk scrunchies, crystal hair vines, and embellished bridal dupattas.",
    image: "https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=800&q=80",
    featured: false,
    displayOrder: 11,
  }
];

export const initialProducts: Product[] = [
  {
    id: "prod-1",
    name: "Gulbahar Embroidered Luxury Lawn 3 Piece",
    nameBn: "গুলবাহার এমব্রয়ডারিড লাক্সারি লন থ্রি-পিস",
    slug: "gulbahar-embroidered-luxury-lawn-3-piece",
    description: "Exquisite festive 3-piece ensemble featuring dense resham and tilla embroidery on luxury Swiss lawn kameez. Paired with a digital printed pure organza dupatta with scalloped borders and tailored cambric cotton trousers.",
    categoryId: "cat-3piece",
    categoryName: "3 Piece",
    categorySlug: "3-piece",
    price: 4850,
    salePrice: 4150,
    discount: 14,
    sku: "LN-3P-001",
    stock: 28,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Sage Mint", "Rose Quartz", "Lilac Mist"],
    colorCodes: ["#A3B899", "#E8A598", "#C8B6D6"],
    images: [
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=900&q=85",
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=900&q=85",
      "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=900&q=85"
    ],
    rating: 4.9,
    reviewCount: 34,
    tags: ["Festive", "Lawn", "3 Piece", "Eid Collection", "Luxury"],
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isTrending: true,
    isOnSale: true,
    fabricDetails: "Shirt: 100% Luxury Swiss Lawn (3.2m), Dupatta: Digital Printed Organza (2.5m), Trouser: Dyed Cambric Cotton (2.5m)",
    careInfo: "Dry clean recommended for the first wash. Gentle cold hand wash separately. Do not bleach or tumble dry. Iron on medium reverse side.",
    createdAt: "2026-03-01T10:00:00Z"
  },
  {
    id: "prod-2",
    name: "Noor-e-Bahar Dhakai Jamdani Handloom Saree",
    nameBn: "নূর-এ-বাহার জামদানি হ্যান্ডলুম শাড়ি",
    slug: "noor-e-bahar-dhakai-jamdani-handloom-saree",
    description: "Authentic 84-count hand-woven Dhakai Jamdani saree with delicate floral 'panna hajar' motifs woven in golden zari and soft crimson threads. Includes unstitched matching blouse piece.",
    categoryId: "cat-saree",
    categoryName: "Saree",
    categorySlug: "saree",
    price: 8500,
    salePrice: 7650,
    discount: 10,
    sku: "LN-SR-002",
    stock: 14,
    sizes: ["Free Size (12 Haat)"],
    colors: ["Ivory Gold", "Royal Crimson", "Emerald Teal"],
    colorCodes: ["#FAF0E6", "#990011", "#004B49"],
    images: [
      "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=900&q=85",
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=900&q=85"
    ],
    rating: 5.0,
    reviewCount: 42,
    tags: ["Jamdani", "Handloom", "Heritage", "Bridal", "Traditional"],
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isTrending: true,
    isOnSale: true,
    fabricDetails: "Fine Egyptian Cotton Thread with Gold Zari weft, Handcrafted in Rupganj, Narayanganj.",
    careInfo: "Strictly dry clean only. Store wrapped in pure muslin cloth with silica gel sachets.",
    createdAt: "2026-02-15T12:00:00Z"
  },
  {
    id: "prod-3",
    name: "Aafiya Dubai Crystal Embroidered Kimono Abaya",
    nameBn: "আফিয়া দুবাই ক্রিস্টাল এমব্রয়ডারিড কিমোনো আবায়া",
    slug: "aafiya-dubai-crystal-embroidered-kimono-abaya",
    description: "Ultra-modest flowing front-open kimono abaya created with original Dubai Nidha matte fabric. Adorned with hand-stitched Austrian crystals along cuffs and collar lapel. Comes with matching belt and premium chiffon sheila.",
    categoryId: "cat-abaya",
    categoryName: "Abaya",
    categorySlug: "abaya",
    price: 4950,
    salePrice: 4450,
    discount: 10,
    sku: "LN-AB-003",
    stock: 22,
    sizes: ["52", "54", "56", "58"],
    colors: ["Onyx Black", "Smoky Mocha", "Desert Olive"],
    colorCodes: ["#1C1C1C", "#705346", "#556B2F"],
    images: [
      "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=900&q=85",
      "https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?w=900&q=85"
    ],
    rating: 4.8,
    reviewCount: 29,
    tags: ["Modest", "Dubai Abaya", "Borka", "Crystal Work", "Nidha"],
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isTrending: true,
    isOnSale: true,
    fabricDetails: "Original Dubai Breathable Nidha Fabric (100% Polyester micro-twill)",
    careInfo: "Cold machine wash on gentle cycle or hand wash inside out. Hang dry immediately. Cool steam iron.",
    createdAt: "2026-03-05T09:00:00Z"
  },
  {
    id: "prod-4",
    name: "Zoya Hand-Block Printed Pure Cotton Kurti",
    nameBn: "জোয়া হ্যান্ড-ব্লক প্রিন্টেড কটন কুর্তি",
    slug: "zoya-hand-block-printed-pure-cotton-kurti",
    description: "Breezy A-line contemporary kurti made with 100% combed breathable cotton. Enhanced with traditional hand-carved wooden block prints, wooden button accents, and neat slit details.",
    categoryId: "cat-kurti",
    categoryName: "Kurti",
    categorySlug: "kurti",
    price: 1850,
    salePrice: 1550,
    discount: 16,
    sku: "LN-KT-004",
    stock: 45,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Indigo Blue", "Mustard Ochre", "Terracotta"],
    colorCodes: ["#2B3E50", "#D99B26", "#C1502E"],
    images: [
      "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=900&q=85",
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=900&q=85"
    ],
    rating: 4.7,
    reviewCount: 51,
    tags: ["Cotton", "Office Wear", "Everyday", "Hand Block", "Summer"],
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    isTrending: false,
    isOnSale: true,
    fabricDetails: "100% Combed Slub Cotton, natural vegetable dyes.",
    careInfo: "Machine wash cold with like colors. Line dry in shade to preserve vibrant natural pigments.",
    createdAt: "2026-03-10T14:20:00Z"
  },
  {
    id: "prod-5",
    name: "Malika Royal Velvet Embroidered Salwar Kameez",
    nameBn: "মালিকা রয়্যাল ভেলভেট এমব্রয়ডারিড সেলোয়ার কামিজ",
    slug: "malika-royal-velvet-embroidered-salwar-kameez",
    description: "Opulent micro-velvet festive winter kameez with intricate Kashmiri tilla embroidery across the neckline, sleeves, and hemline. Matched with brocade raw-silk cigarette pants and a gold organza dupatta.",
    categoryId: "cat-salwar",
    categoryName: "Salwar Kameez",
    categorySlug: "salwar-kameez",
    price: 7200,
    salePrice: 6480,
    discount: 10,
    sku: "LN-SK-005",
    stock: 16,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Deep Plum", "Midnight Emerald", "Ruby Wine"],
    colorCodes: ["#481F38", "#0B3C2B", "#721422"],
    images: [
      "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=900&q=85",
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=900&q=85"
    ],
    rating: 4.9,
    reviewCount: 19,
    tags: ["Velvet", "Wedding Guest", "Winter Luxury", "Party Wear"],
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isTrending: true,
    isOnSale: true,
    fabricDetails: "Pure 9000 Micro Velvet Top, Raw Silk Bottom, Embroidered Organza Dupatta.",
    careInfo: "Dry clean only. Do not iron directly on the velvet pile; steam gently.",
    createdAt: "2026-01-20T11:30:00Z"
  },
  {
    id: "prod-6",
    name: "Meher Turkish Georgette Crinkle Hijab",
    nameBn: "মেহের তুর্কি জর্জেট ক্রিঙ্কল হিজাব",
    slug: "meher-turkish-georgette-crinkle-hijab",
    description: "Signature non-slip, lightweight Turkish bubble georgette hijab. Needs zero pins to stay securely draped all day with a sophisticated soft texture and elegant fall.",
    categoryId: "cat-hijab",
    categoryName: "Hijab",
    categorySlug: "hijab",
    price: 650,
    salePrice: 520,
    discount: 20,
    sku: "LN-HJ-006",
    stock: 120,
    sizes: ["Standard Maxi (85 x 200 cm)"],
    colors: ["Muted Almond", "Dusty Mauve", "Pistachio", "Charcoal"],
    colorCodes: ["#EED9C4", "#B88E8D", "#93C572", "#36454F"],
    images: [
      "https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?w=900&q=85",
      "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=900&q=85"
    ],
    rating: 4.8,
    reviewCount: 96,
    tags: ["Hijab", "Georgette", "Non-Slip", "Daily Modest", "Summer Friendly"],
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    isTrending: true,
    isOnSale: true,
    fabricDetails: "100% Premium Bubble Crinkle Georgette, imported from Istanbul.",
    careInfo: "Hand wash in cool water with mild shampoo. Air dry in shade. No ironing required.",
    createdAt: "2026-03-12T08:00:00Z"
  },
  {
    id: "prod-7",
    name: "Roshni Zari Embroidered Single Kameez",
    nameBn: "রোশনি জরি এমব্রয়ডারিড সিঙ্গেল কামিজ",
    slug: "roshni-zari-embroidered-single-kameez",
    description: "Charming straight-cut kameez crafted with textured jacquard cotton. Features fine antique zari needlework on the yoke, bell sleeves and delicate button lace styling.",
    categoryId: "cat-kameez",
    categoryName: "Kameez",
    categorySlug: "kameez",
    price: 2450,
    salePrice: 2150,
    discount: 12,
    sku: "LN-KM-007",
    stock: 35,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Butterscotch Yellow", "Peacock Green", "Ivory White"],
    colorCodes: ["#E0A96D", "#005F56", "#FBFBF9"],
    images: [
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=900&q=85",
      "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=900&q=85"
    ],
    rating: 4.7,
    reviewCount: 23,
    tags: ["Kameez", "Single Piece", "Festive Ready", "Cotton Jacquard"],
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isTrending: true,
    isOnSale: true,
    fabricDetails: "Self-textured Cotton Jacquard with pure viscose thread embroidery.",
    careInfo: "Hand wash separately in lukewarm water. Iron inside out on medium heat.",
    createdAt: "2026-03-08T15:30:00Z"
  },
  {
    id: "prod-8",
    name: "Bano Velvet Hand-Embroidered Bridal Potli Clutch",
    nameBn: "বানো ভেলভেট হ্যান্ড-এমব্রয়ডারিড ব্রাইডাল পোটলি",
    slug: "bano-velvet-hand-embroidered-bridal-potli-clutch",
    description: "Stunning handcrafted traditional festive potli bag encrusted with pearls, dabka, and zardozi threadwork. Features beaded drawstrings, silk tassel accents, and a detachable pearl strap.",
    categoryId: "cat-bags",
    categoryName: "Bags",
    categorySlug: "bags",
    price: 2800,
    salePrice: 2450,
    discount: 12,
    sku: "LN-BG-008",
    stock: 18,
    sizes: ["One Size (9x7 inches)"],
    colors: ["Crimson Red", "Antique Gold", "Midnight Navy"],
    colorCodes: ["#8B0000", "#D4AF37", "#000080"],
    images: [
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=900&q=85",
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=900&q=85"
    ],
    rating: 4.9,
    reviewCount: 38,
    tags: ["Bags", "Potli", "Clutch", "Bridal", "Handmade"],
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isTrending: false,
    isOnSale: true,
    fabricDetails: "Micro Velvet with satin lining and Austrian faux pearls.",
    careInfo: "Wipe clean with a soft dry cloth. Store in dust bag away from moisture.",
    createdAt: "2026-02-18T16:00:00Z"
  },
  {
    id: "prod-9",
    name: "Shaahi Kundan & Pearl Choker Jewellery Set",
    nameBn: "শাহী কুন্দন ও মুক্তার চোকার জুয়েলারি সেট",
    slug: "shaahi-kundan-and-pearl-choker-jewellery-set",
    description: "Royal 22K gold-micron plated Kundan choker necklace accompanied by matching chandelier earrings and a graceful maang tikka. Strung with natural freshwater baroque seed pearls.",
    categoryId: "cat-jewellery",
    categoryName: "Jewellery",
    categorySlug: "jewellery",
    price: 3650,
    salePrice: 3200,
    discount: 12,
    sku: "LN-JW-009",
    stock: 20,
    sizes: ["Adjustable Dori"],
    colors: ["Antique Gold & Pearl", "Emerald Green Kundan", "Ruby Red Kundan"],
    colorCodes: ["#CFB53B", "#046307", "#9E1B32"],
    images: [
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=900&q=85",
      "https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=900&q=85"
    ],
    rating: 5.0,
    reviewCount: 57,
    tags: ["Jewellery", "Kundan", "Choker", "Wedding", "Bridal Collection"],
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isTrending: true,
    isOnSale: true,
    fabricDetails: "Brass base, 22K Micron Gold plating, Grade-A Kundan stones, and faux shell pearls.",
    careInfo: "Keep away from perfumes, hair sprays and direct water. Store in airtight zip pouch.",
    createdAt: "2026-02-28T10:15:00Z"
  },
  {
    id: "prod-10",
    name: "Chandni Zardozi Festive Kolhapuri Sandals",
    nameBn: "চাঁদনি জারদৌসি ফেস্টিভ কোলহাপুরি স্যান্ডেল",
    slug: "chandni-zardozi-festive-kolhapuri-sandals",
    description: "Handmade genuine soft leather padded kolhapuri sandals embellished with copper dabka work and tiny ghungroo beads. Extra cushioned memory-foam footbed for all-day wedding comfort.",
    categoryId: "cat-shoes",
    categoryName: "Shoes",
    categorySlug: "shoes",
    price: 2650,
    salePrice: 2250,
    discount: 15,
    sku: "LN-SH-010",
    stock: 25,
    sizes: ["36", "37", "38", "39", "40", "41"],
    colors: ["Champagne Gold", "Rose Metallic", "Silver Glow"],
    colorCodes: ["#EAD8B1", "#C7A29E", "#D8D8D8"],
    images: [
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=900&q=85",
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=900&q=85"
    ],
    rating: 4.8,
    reviewCount: 31,
    tags: ["Shoes", "Kolhapuri", "Festive", "Comfort", "Handcrafted"],
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isTrending: true,
    isOnSale: true,
    fabricDetails: "Top: Silk & Zardozi embroidery, Sole: Soft genuine buff leather with anti-slip rubber grip.",
    careInfo: "Clean with damp cloth. Do not soak in water. Polish periodically with leather balm.",
    createdAt: "2026-03-02T13:45:00Z"
  },
  {
    id: "prod-11",
    name: "Amanah Matte Satin Premium Silk Hijab",
    nameBn: "আমানাহ ম্যাট সাটিন প্রিমিয়াম সিল্ক হিজাব",
    slug: "amanah-matte-satin-premium-silk-hijab",
    description: "Subtle pearlescent glow with zero slippery sheen. This Turkish matte silk hijab drapes luxuriously for festive gatherings, Eid, and bridal occasions.",
    categoryId: "cat-hijab",
    categoryName: "Hijab",
    categorySlug: "hijab",
    price: 950,
    salePrice: 850,
    discount: 10,
    sku: "LN-HJ-011",
    stock: 60,
    sizes: ["Maxi (75 x 195 cm)"],
    colors: ["Blush Champagne", "Muted Sage", "Midnight Pearl"],
    colorCodes: ["#E3C5B5", "#8E9E82", "#2B303A"],
    images: [
      "https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?w=900&q=85",
      "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=900&q=85"
    ],
    rating: 4.9,
    reviewCount: 45,
    tags: ["Hijab", "Silk Satin", "Festive Hijab", "Luxury Modest"],
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isTrending: false,
    isOnSale: false,
    fabricDetails: "Silk blend with textured inner grip back.",
    careInfo: "Hand wash gently in cold water with silk detergent. Low steam iron on reverse side.",
    createdAt: "2026-02-10T11:00:00Z"
  },
  {
    id: "prod-12",
    name: "Niloufar Organza Floral Designer Saree",
    nameBn: "নিলুফার অর্গানজা ফ্লোরাল ডিজাইনার শাড়ি",
    slug: "niloufar-organza-floral-designer-saree",
    description: "Whisper-light pure silk organza saree painted with soft pastel water-color blooms. Highlighted with scalloped cut-work embroidery borders and seed pearl tassels on the pallu.",
    categoryId: "cat-saree",
    categoryName: "Saree",
    categorySlug: "saree",
    price: 6800,
    salePrice: 5950,
    discount: 12,
    sku: "LN-SR-012",
    stock: 12,
    sizes: ["Free Size (12 Haat)"],
    colors: ["Pastel Peach", "Mint Blossom", "Lavender Dream"],
    colorCodes: ["#FFDAB9", "#B2DFDB", "#E6E6FA"],
    images: [
      "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=900&q=85",
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=900&q=85"
    ],
    rating: 4.9,
    reviewCount: 27,
    tags: ["Organza", "Saree", "Pastel", "Floral", "Party Wear"],
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isTrending: true,
    isOnSale: true,
    fabricDetails: "Pure Silk Organza with digital floral print and cutwork embroidery.",
    careInfo: "Dry clean only. Roll fold to avoid creasing delicate organza fibers.",
    createdAt: "2026-03-04T17:00:00Z"
  },
  {
    id: "prod-13",
    name: "Zinnia Printed Lawn 3 Piece with Chiffon Dupatta",
    nameBn: "জিনিয়া প্রিন্টেড লন ৩ পিস শিফন ওড়নাসহ",
    slug: "zinnia-printed-lawn-3-piece-with-chiffon-dupatta",
    description: "Vibrant bohemian geometric and floral digital printed lawn suit. Lightweight, exceptionally breathable, with a sheer crinkle chiffon dupatta tailored for hot summer days in Bangladesh.",
    categoryId: "cat-3piece",
    categoryName: "3 Piece",
    categorySlug: "3-piece",
    price: 2950,
    salePrice: 2650,
    discount: 10,
    sku: "LN-3P-013",
    stock: 50,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Teal Splash", "Coral Sunshine", "Berry Burst"],
    colorCodes: ["#008080", "#FF7F50", "#800020"],
    images: [
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=900&q=85",
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=900&q=85"
    ],
    rating: 4.6,
    reviewCount: 68,
    tags: ["3 Piece", "Summer Lawn", "Chiffon Dupatta", "Affordable Fashion"],
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isTrending: false,
    isOnSale: true,
    fabricDetails: "100% Fine Combed Lawn Kameez & Trouser, Bemberg Chiffon Dupatta.",
    careInfo: "Cold gentle machine wash. Do not wring. Shade dry recommended.",
    createdAt: "2026-02-05T09:30:00Z"
  },
  {
    id: "prod-14",
    name: "Raasleela Kashmiri Aari Embroidered Kurti",
    nameBn: "রাসলীলা কাশ্মিরি আরি এমব্রয়ডারি কুর্তি",
    slug: "raasleela-kashmiri-aari-embroidered-kurti",
    description: "Detailed traditional Kashmiri chain-stitch Aari needlework covering the yoke and sleeves of this soft khadi-cotton kurti. Pairs effortlessly with palazzos or denim.",
    categoryId: "cat-kurti",
    categoryName: "Kurti",
    categorySlug: "kurti",
    price: 2150,
    salePrice: 1850,
    discount: 14,
    sku: "LN-KT-014",
    stock: 32,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Off-White & Red", "Mustard Yellow", "Olive Green"],
    colorCodes: ["#FDFBF7", "#E1AD01", "#556B2F"],
    images: [
      "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=900&q=85",
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=900&q=85"
    ],
    rating: 4.8,
    reviewCount: 22,
    tags: ["Kurti", "Kashmiri", "Aari Work", "Ethnic Chic"],
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isTrending: true,
    isOnSale: true,
    fabricDetails: "Breathable Khadi Cotton blend.",
    careInfo: "Hand wash in cold water. Iron on reverse side using medium heat.",
    createdAt: "2026-03-06T12:15:00Z"
  },
  {
    id: "prod-15",
    name: "Maryam Layered Front-Open Abaya with Belt",
    nameBn: "মরিয়ম লেয়ার্ড ফ্রন্ট-ওপেন আবায়া বেল্টসহ",
    slug: "maryam-layered-front-open-abaya-with-belt",
    description: "Minimalist two-tier cascading layer abaya featuring soft pleated balloon sleeves, discreet side pockets, and an adjustable fabric tie-belt. Comfortable and elegant.",
    categoryId: "cat-abaya",
    categoryName: "Abaya",
    categorySlug: "abaya",
    price: 3850,
    salePrice: 3450,
    discount: 10,
    sku: "LN-AB-015",
    stock: 24,
    sizes: ["52", "54", "56"],
    colors: ["Dusty Rose", "Classic Black", "Earl Grey"],
    colorCodes: ["#DCAE96", "#1A1A1A", "#6D6875"],
    images: [
      "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=900&q=85",
      "https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?w=900&q=85"
    ],
    rating: 4.7,
    reviewCount: 30,
    tags: ["Abaya", "Modest Fashion", "Minimalist", "Everyday Borka"],
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isTrending: false,
    isOnSale: true,
    fabricDetails: "Korean Cey Crepe fabric, wrinkle-resistant and breathable.",
    careInfo: "Machine washable. Hang immediately on hanger to dry.",
    createdAt: "2026-01-28T14:40:00Z"
  },
  {
    id: "prod-16",
    name: "Shondha Meenakari Handcrafted Jhumka Earrings",
    nameBn: "সন্ধ্যা মীনাকারি হস্তশিল্প ঝুমকা",
    slug: "shondha-meenakari-handcrafted-jhumka-earrings",
    description: "Traditional dome-shaped jhumkas adorned with radiant green and ruby enamel meenakari work, micro pearls, and delicate bell drops. Gold polished finish.",
    categoryId: "cat-jewellery",
    categoryName: "Jewellery",
    categorySlug: "jewellery",
    price: 1450,
    salePrice: 1250,
    discount: 14,
    sku: "LN-JW-016",
    stock: 35,
    sizes: ["Standard (3 inches)"],
    colors: ["Ruby & Emerald Gold", "Pastel Mint Gold"],
    colorCodes: ["#B22222", "#98FF98"],
    images: [
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=900&q=85",
      "https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=900&q=85"
    ],
    rating: 4.9,
    reviewCount: 62,
    tags: ["Jewellery", "Jhumka", "Meenakari", "Traditional", "Gift"],
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isTrending: true,
    isOnSale: true,
    fabricDetails: "Lead and nickel-free brass alloy, high-grade enamel.",
    careInfo: "Wipe with a soft cotton swab after wear. Keep in dry box.",
    createdAt: "2026-02-12T16:00:00Z"
  },
  {
    id: "prod-17",
    name: "Tasfia Structured Vegan Leather Everyday Tote",
    nameBn: "তাসফিয়া ভেগান লেদার এভরিডে টোট ব্যাগ",
    slug: "tasfia-structured-vegan-leather-everyday-tote",
    description: "Spacious multi-compartment structured tote crafted in scratch-resistant saffiano-textured vegan leather. Easily holds a 13-inch laptop, planner, cosmetics, and water bottle.",
    categoryId: "cat-bags",
    categoryName: "Bags",
    categorySlug: "bags",
    price: 3450,
    salePrice: 2950,
    discount: 14,
    sku: "LN-BG-017",
    stock: 20,
    sizes: ["Large (14 x 11 x 5 inches)"],
    colors: ["Cognac Tan", "Midnight Black", "Powder Nude"],
    colorCodes: ["#9A532C", "#1E1E1E", "#E6D2B5"],
    images: [
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=900&q=85",
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=900&q=85"
    ],
    rating: 4.8,
    reviewCount: 19,
    tags: ["Bags", "Tote", "Office Bag", "Vegan Leather", "Spacious"],
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isTrending: true,
    isOnSale: true,
    fabricDetails: "Premium Saffiano PU Leather, Gold-finish metal hardware, waterproof inner lining.",
    careInfo: "Wipe clean with a damp microfiber cloth.",
    createdAt: "2026-03-09T18:20:00Z"
  },
  {
    id: "prod-18",
    name: "Parijat Handloom Pure Katan Silk Party Saree",
    nameBn: "পারিজাত হ্যান্ডলুম পিওর কাতান সিল্ক পার্টি শাড়ি",
    slug: "parijat-handloom-pure-katan-silk-party-saree",
    description: "Heritage Benarasi Katan silk saree woven with royal paisley 'kalga' motifs in antique copper zari. Rich pallu with dense zari brocade weave for wedding receptions.",
    categoryId: "cat-saree",
    categoryName: "Saree",
    categorySlug: "saree",
    price: 11500,
    salePrice: 9950,
    discount: 13,
    sku: "LN-SR-018",
    stock: 8,
    sizes: ["Free Size (12 Haat)"],
    colors: ["Rani Pink", "Royal Blue", "Forest Green"],
    colorCodes: ["#E72B76", "#002366", "#228B22"],
    images: [
      "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=900&q=85",
      "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=900&q=85"
    ],
    rating: 5.0,
    reviewCount: 18,
    tags: ["Katan Silk", "Saree", "Bridal", "Heritage", "Reception"],
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isTrending: false,
    isOnSale: true,
    fabricDetails: "100% Pure Mulberry Silk with Copper Zari weft.",
    careInfo: "Strictly dry clean. Wrap in cotton sari covers.",
    createdAt: "2026-01-15T09:00:00Z"
  },
  {
    id: "prod-19",
    name: "Zeenat Mirror Work Festive Salwar Suit",
    nameBn: "জিনাত মিরর ওয়ার্ক ফেস্টিভ সেলোয়ার স্যুট",
    slug: "zeenat-mirror-work-festive-salwar-suit",
    description: "Captivating Georgette salwar suit with original foil mirror embroidery and threadwork on the neckline and daman. Comes stitched with silk lining, matched with flared palazzo pants.",
    categoryId: "cat-salwar",
    categoryName: "Salwar Kameez",
    categorySlug: "salwar-kameez",
    price: 5400,
    salePrice: 4750,
    discount: 12,
    sku: "LN-SK-019",
    stock: 18,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Sunset Coral", "Mustard Festive", "Teal Blue"],
    colorCodes: ["#FF6F61", "#E5A93B", "#008B8B"],
    images: [
      "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=900&q=85",
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=900&q=85"
    ],
    rating: 4.8,
    reviewCount: 26,
    tags: ["Mirror Work", "Salwar Suit", "Festive Ready", "Georgette"],
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isTrending: true,
    isOnSale: true,
    fabricDetails: "Faux Georgette with Shantoon inner lining.",
    careInfo: "Dry clean recommended.",
    createdAt: "2026-03-03T11:45:00Z"
  },
  {
    id: "prod-20",
    name: "Luxury Magnetic Hijab Pins & Velvet Scrunchie Set",
    nameBn: "ম্যাগনেটিক হিজাব পিন ও ভেলভেট স্ক্রাঞ্চি সেট",
    slug: "luxury-magnetic-hijab-pins-and-velvet-scrunchie-set",
    description: "Snag-free ultra-strong neodymium magnetic hijab pins set (4 metallic shades: Rose Gold, Matte Gold, Silver, Gunmetal) paired with 2 volumizing soft velvet scrunchies.",
    categoryId: "cat-accessories",
    categoryName: "Accessories",
    categorySlug: "accessories",
    price: 750,
    salePrice: 590,
    discount: 21,
    sku: "LN-AC-020",
    stock: 80,
    sizes: ["Standard Set (4 Pins + 2 Scrunchies)"],
    colors: ["Metallic Trio & Nude Scrunchies"],
    colorCodes: ["#B76E79"],
    images: [
      "https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=900&q=85",
      "https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?w=900&q=85"
    ],
    rating: 5.0,
    reviewCount: 84,
    tags: ["Accessories", "Hijab Pins", "Magnetic", "Scrunchies", "Essentials"],
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isTrending: true,
    isOnSale: true,
    fabricDetails: "Nickel-coated rare-earth magnets, high-stretch velvet.",
    careInfo: "Keep away from electronic pacemakers and credit card magnetic strips.",
    createdAt: "2026-03-11T13:00:00Z"
  },
  {
    id: "prod-21",
    name: "Noor Cushion Sole Festive Kitten Heels",
    nameBn: "নূর কুশনড সোল ফেস্টিভ কিটেন হিলস",
    slug: "noor-cushion-sole-festive-kitten-heels",
    description: "Comfort meets couture: 2.2-inch comfortable kitten heels styled with criss-cross metallic straps, gold hardware buckle, and triple-density latex memory footbed.",
    categoryId: "cat-shoes",
    categoryName: "Shoes",
    categorySlug: "shoes",
    price: 3200,
    salePrice: 2750,
    discount: 14,
    sku: "LN-SH-021",
    stock: 22,
    sizes: ["36", "37", "38", "39", "40"],
    colors: ["Muted Gold", "Rose Champagne", "Jet Black"],
    colorCodes: ["#D4AF37", "#B76E79", "#111111"],
    images: [
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=900&q=85",
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=900&q=85"
    ],
    rating: 4.7,
    reviewCount: 29,
    tags: ["Shoes", "Heels", "Kitten Heels", "Party Footwear"],
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isTrending: true,
    isOnSale: true,
    fabricDetails: "Metallic Vegan Leather upper, rubber compound sole.",
    careInfo: "Wipe with damp cloth and polish with clear wax sponge.",
    createdAt: "2026-03-07T10:15:00Z"
  },
  {
    id: "prod-22",
    name: "Eshaan Organza Hand-Embroidered Single Kameez",
    nameBn: "এশান অর্গানজা হ্যান্ড-এমব্রয়ডারিড সিঙ্গেল কামিজ",
    slug: "eshaan-organza-hand-embroidered-single-kameez",
    description: "Contemporary flared organza shirt with attached pure cotton silk inner slip. Featuring delicate white thread floral cutwork vines and statement balloon sleeves.",
    categoryId: "cat-kameez",
    categoryName: "Kameez",
    categorySlug: "kameez",
    price: 3250,
    salePrice: 2850,
    discount: 12,
    sku: "LN-KM-022",
    stock: 20,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Lavender Whisper", "Powder Blue", "Mint Frost"],
    colorCodes: ["#E6E6FA", "#B0E0E6", "#E0F2F1"],
    images: [
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=900&q=85",
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=900&q=85"
    ],
    rating: 4.9,
    reviewCount: 17,
    tags: ["Kameez", "Organza", "Cutwork", "Pastel", "Party"],
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isTrending: true,
    isOnSale: true,
    fabricDetails: "Silk Organza outer with Stitched Cotton Viscose Inner.",
    careInfo: "Dry clean only. Steam iron gently.",
    createdAt: "2026-03-14T09:30:00Z"
  }
];

export const initialReviews: Review[] = [
  {
    id: "rev-1",
    productId: "prod-1",
    userName: "Nusrat Jahan",
    userCity: "Dhanmondi, Dhaka",
    rating: 5,
    comment: "কাপড়ের কোয়ালিটি ও এমব্রয়ডারি সত্যিই অসাধারণ! ছবিতে যেমন দেখেছি হুবহু তেমনই পেয়েছি। মাত্র ২ দিনে ডেলিভারি পেয়েছি।",
    isVerified: true,
    isApproved: true,
    createdAt: "2026-03-08T11:20:00Z"
  },
  {
    id: "rev-2",
    productId: "prod-1",
    userName: "Farhana Islam",
    userCity: "Chattogram",
    rating: 5,
    comment: "The organza dupatta is so soft and elegant. Got so many compliments at my cousin's Holud! Highly recommended.",
    isVerified: true,
    isApproved: true,
    createdAt: "2026-03-05T15:40:00Z"
  },
  {
    id: "rev-3",
    productId: "prod-2",
    userName: "Tasneem Rahman",
    userCity: "Uttara, Dhaka",
    rating: 5,
    comment: "জামদানি শাড়ির বুনন খুব নিখুঁত। নরম সুতি এবং পরতে খুব আরামদায়ক। লুনারা ফ্যাশনের প্যাকেজিংও খুব প্রিমিয়াম ছিল।",
    isVerified: true,
    isApproved: true,
    createdAt: "2026-03-02T16:10:00Z"
  },
  {
    id: "rev-4",
    productId: "prod-6",
    userName: "Samia Akter",
    userCity: "Sylhet",
    rating: 5,
    comment: "Best georgette hijab in BD right now! Pin charai mathay thake, ar shorir garam hoy na. Ordered 3 more colors.",
    isVerified: true,
    isApproved: true,
    createdAt: "2026-03-13T09:00:00Z"
  },
  {
    id: "rev-5",
    productId: "prod-9",
    userName: "Sadia Chowdhury",
    userCity: "Mirpur, Dhaka",
    rating: 5,
    comment: "কুন্দন সেটটি দেখতে একদম আসল সোনার মতো ভারী ও রাজকীয়। বিয়ের অনুষ্ঠানের জন্য পারফেক্ট!",
    isVerified: true,
    isApproved: true,
    createdAt: "2026-03-06T13:30:00Z"
  }
];

export const initialCoupons: Coupon[] = [
  {
    id: "coup-1",
    code: "LUNARA10",
    type: "PERCENTAGE",
    discount: 10,
    minOrder: 1500,
    maxDiscount: 500,
    isActive: true,
    timesUsed: 142
  },
  {
    id: "coup-2",
    code: "EIDSPECIAL",
    type: "FIXED_AMOUNT",
    discount: 300,
    minOrder: 3000,
    isActive: true,
    timesUsed: 89
  },
  {
    id: "coup-3",
    code: "FIRSTORDER",
    type: "PERCENTAGE",
    discount: 15,
    minOrder: 1200,
    maxDiscount: 400,
    isActive: true,
    timesUsed: 310
  }
];

export const initialSettings: StoreSettings = {
  brandName: "LUNARA FASHION",
  brandTagline: "Elegance in Every Thread",
  brandTaglineBn: "প্রতিটি সুতোয় আভিজাত্যের ছোঁয়া",
  currency: "BDT",
  currencySymbol: "৳",
  deliveryCharges: {
    dhakaCity: 70,
    subDhaka: 100,
    outsideDhaka: 120
  },
  supportPhone: "+880 1712-345678",
  supportEmail: "support@lunarafashion.com",
  showroomAddress: "House 42, Road 11, Block D, Banani, Dhaka-1213",
  showroomAddressBn: "বাড়ি ৪২, রোড ১১, ব্লক ডি, বনানী, ঢাকা-১২১৩",
  noticeBanner: "🎉 Special Spring Offer: Use code LUNARA10 for 10% off! Cash on delivery across all 64 districts.",
  noticeBannerBn: "🎉 বসন্ত উৎসব অফার: LUNARA10 কুপন কোডে ১০% ছাড়! ৬৪ জেলায় ক্যাশ অন ডেলিভারি সুবিধা।",
  socialLinks: {
    facebook: "https://facebook.com/lunarafashion",
    instagram: "https://instagram.com/lunarafashion",
    whatsapp: "https://wa.me/8801712345678",
    youtube: "https://youtube.com/@lunarafashion"
  }
};

export const initialUsers: User[] = [
  {
    id: "user-admin-1",
    name: "Lunara Admin",
    email: "admin@lunarafashion.com",
    phone: "+880 1711-000111",
    role: "ADMIN",
    createdAt: "2026-01-01T00:00:00Z"
  },
  {
    id: "user-customer-1",
    name: "Sumaiya Haque",
    email: "sumaiya@gmail.com",
    phone: "+880 1819-223344",
    role: "CUSTOMER",
    addresses: [
      {
        id: "addr-1",
        userId: "user-customer-1",
        fullName: "Sumaiya Haque",
        phone: "01819223344",
        division: "Dhaka",
        district: "Dhaka",
        upazila: "Gulshan-1",
        fullAddress: "Flat 4B, House 12, Road 23, Gulshan-1, Dhaka-1212",
        deliveryZone: "DHAKA_CITY",
        isDefault: true
      }
    ],
    createdAt: "2026-02-01T10:00:00Z"
  }
];

export const initialOrders: Order[] = [
  {
    id: "ord-1",
    orderNumber: "LN-84921",
    userId: "user-customer-1",
    customerName: "Sumaiya Haque",
    customerPhone: "01819223344",
    customerEmail: "sumaiya@gmail.com",
    shippingAddress: "Flat 4B, House 12, Road 23, Gulshan-1, Dhaka-1212",
    division: "Dhaka",
    district: "Dhaka",
    upazila: "Gulshan-1",
    deliveryZone: "DHAKA_CITY",
    deliveryNote: "Please call before delivering.",
    items: [
      {
        id: "item-1",
        productId: "prod-1",
        productName: "Gulbahar Embroidered Luxury Lawn 3 Piece",
        productImage: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=900&q=85",
        size: "M",
        color: "Sage Mint",
        unitPrice: 4150,
        quantity: 1,
        totalPrice: 4150
      },
      {
        id: "item-2",
        productId: "prod-6",
        productName: "Meher Turkish Georgette Crinkle Hijab",
        productImage: "https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?w=900&q=85",
        size: "Standard Maxi (85 x 200 cm)",
        color: "Muted Almond",
        unitPrice: 520,
        quantity: 2,
        totalPrice: 1040
      }
    ],
    subtotal: 5190,
    deliveryFee: 70,
    discountAmount: 500,
    couponCode: "LUNARA10",
    grandTotal: 4760,
    paymentMethod: "COD",
    paymentStatus: "UNPAID",
    status: "PROCESSING",
    trackingNumber: "PATHAO-8941029",
    createdAt: "2026-03-18T14:20:00Z",
    statusHistory: [
      {
        id: "sh-1",
        status: "PENDING",
        note: "Order placed via website by customer.",
        timestamp: "2026-03-18T14:20:00Z",
        updatedBy: "System"
      },
      {
        id: "sh-2",
        status: "CONFIRMED",
        note: "Order confirmed over phone by customer support team.",
        timestamp: "2026-03-18T15:10:00Z",
        updatedBy: "Admin Support"
      },
      {
        id: "sh-3",
        status: "PROCESSING",
        note: "Products picked and packaged in Banani Hub warehouse.",
        timestamp: "2026-03-19T09:30:00Z",
        updatedBy: "Warehouse Admin"
      }
    ]
  },
  {
    id: "ord-2",
    orderNumber: "LN-84803",
    customerName: "Ayesha Siddiqua",
    customerPhone: "01712998877",
    customerEmail: "ayesha@yahoo.com",
    shippingAddress: "House 15, Road 4, Nasirabad Housing Society, Chattogram",
    division: "Chattogram",
    district: "Chattogram",
    upazila: "Nasirabad",
    deliveryZone: "OUTSIDE_DHAKA",
    items: [
      {
        id: "item-3",
        productId: "prod-2",
        productName: "Noor-e-Bahar Dhakai Jamdani Handloom Saree",
        productImage: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=900&q=85",
        size: "Free Size (12 Haat)",
        color: "Ivory Gold",
        unitPrice: 7650,
        quantity: 1,
        totalPrice: 7650
      }
    ],
    subtotal: 7650,
    deliveryFee: 120,
    discountAmount: 300,
    couponCode: "EIDSPECIAL",
    grandTotal: 7470,
    paymentMethod: "COD",
    paymentStatus: "PAID",
    status: "DELIVERED",
    trackingNumber: "STEADFAST-991823",
    createdAt: "2026-03-14T11:00:00Z",
    statusHistory: [
      {
        id: "sh-4",
        status: "PENDING",
        note: "Order placed by customer.",
        timestamp: "2026-03-14T11:00:00Z",
        updatedBy: "System"
      },
      {
        id: "sh-5",
        status: "CONFIRMED",
        note: "Confirmed by admin.",
        timestamp: "2026-03-14T11:30:00Z",
        updatedBy: "Admin"
      },
      {
        id: "sh-6",
        status: "PROCESSING",
        note: "Quality inspected.",
        timestamp: "2026-03-14T14:00:00Z",
        updatedBy: "Admin"
      },
      {
        id: "sh-7",
        status: "SHIPPED",
        note: "Handed over to Steadfast courier.",
        timestamp: "2026-03-15T10:00:00Z",
        updatedBy: "Courier"
      },
      {
        id: "sh-8",
        status: "DELIVERED",
        note: "Cash collected and parcel received by customer.",
        timestamp: "2026-03-17T16:45:00Z",
        updatedBy: "Delivery Agent"
      }
    ]
  }
];
